<a href="https://colab.research.google.com/github/whkaikai/-python-/blob/main/2301551_64_Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dictionaries

## Basic of Dictionaries

A dictionary is an unordered collection of pairs of key and value.

`{2301170:'COMP PROG', 2301551:'PROG LANG'}` is a collection of two pairs of key and value:
* the key `2301170` is associated with the value `'COMP PROG'`
* the key `2301551` is associated with the value `'PROG LANG'`

Given a key in a dictionary, we can get the value assocaited to the key, as shown below.

In [ ]:
cName = {2301170:'COMP PROG', 2301172:'COMP PROG LAB', 2301380:'PROG LANG PRIN', 2301551:'PROG LANG'}
print(cName[2301551])

PROG LANG


All keys in a dictionary must be unique, i.e. a key cannot be associated to more than one value. If two values are assigned to the same key, one value will replace the other.

In [ ]:
cName = {2301170:'COMP PROG', 2301170:'COMP PROG LAB', 2301551:'PROG LANG'}
print(cName)

{2301170: 'COMP PROG LAB', 2301551: 'PROG LANG'}


In dictionaries, keys must be of *immutable* types, i.e. integers, floats, strings, and tuples.  However, lists and dictionaries are mutable objects and cannot use used as keys.

The following example uses student number and course number combined in a tuple as a key.

In [ ]:
grade = {(6212567823, 2301170):3.5, (6212567823, 2301172):4.0, (6120007823, 2301551):4.0}
print(grade[(6212567823, 2301172)])
print(grade[6212567823, 2301172])   # parentheses of the tuple can be omitted

4.0
4.0


### Add a Key-value Pair into a Dictionary

A new key-value pair can be added in a dictionary using assignment statement as follows:

In [ ]:
cName = {2301170:'COMP PROG', 2301172:'COMP PROG LAB', 2301380:'PROG LANG PRIN', 2301551:'PROG LANG'}
cName[2301552]='PRIN DATA STR'
print(cName)

{2301170: 'COMP PROG', 2301172: 'COMP PROG LAB', 2301380: 'PROG LANG PRIN', 2301551: 'PROG LANG', 2301552: 'PRIN DATA STR'}


This can also be used to change the value associated to a key. If there is another value associated to the key in the dictionary, the new value will replace the old value for that key.

In [ ]:
cName = {2301170:'COMP PROG', 2301172:'COMP PROG LAB', 2301380:'PROG LANG PRIN', 2301551:'PROG LANG'}
cName[2301172]='LAB'
print(cName)

{2301170: 'COMP PROG', 2301172: 'LAB', 2301380: 'PROG LANG PRIN', 2301551: 'PROG LANG'}


### Delete a Key-value Pair from a Dictionary

`del` can also be used to delete a key-value pair in a dictionary.

In [ ]:
cName = {2301170:'COMP PROG', 2301172:'COMP PROG LAB', 2301380:'PROG LANG PRIN', 2301551:'PROG LANG'}
del(cName[2301170])
print(cName)

{2301172: 'COMP PROG LAB', 2301380: 'PROG LANG PRIN', 2301551: 'PROG LANG'}


### Update a Dictionary with Another Dictionary

We can add pairs of key-value in one dictionary into another, using the function `update`.  In the case that there are the same key in both dictionaries, the new one will replace the old one. 

In [ ]:
cName = {2301170:'COMP PROG', 2301172:'COMP PROG LAB', 2301551:'P'}
gradcName = {2301551:'PROG LANG', 2301552:'PRIN DATA STR'}
cName.update(gradcName)
print(cName)
print(gradcName)

{2301170: 'COMP PROG', 2301172: 'COMP PROG LAB', 2301551: 'PROG LANG', 2301552: 'PRIN DATA STR'}
{2301551: 'PROG LANG', 2301552: 'PRIN DATA STR'}


In [ ]:
student = {}
for i in range(2):
  text = input('Enter your ID and name : ').split(' ')
  student[text[0]] = text[1]+" "+text[2]
print(student)

Enter your ID and name : 4 a b
Enter your ID and name : 9 bbb mmm
{'4': 'a b', '9': 'bbb mmm'}


## Use of Dictionaries

A dictionary can be used to to store the assocaition beween a key and a value, and then use the key to access the associated value.  The following example uses a dictionary to store course name and number of credits associated with the course number.

In [ ]:
courses = {2301551:['PROG LANG', 3], 2301552:['PRIN DATA STR', 3]}
cID = int(input('Enter course number:'))
print(courses[cID])
print(cID,"'s name is",courses[cID][0],'. (',courses[cID][1],'credits)')

Enter course number:2301552
['PRIN DATA STR', 3]
2301552 's name is PRIN DATA STR . ( 3 credits)


Sometimes, we want to use a combination of values as the key of a dictionary.  For example, the key of a dictionary that stores the transcript of a student is the combination of course number, semester and year.

In [ ]:
transcript = {(2301551, 1, 2562):'S', (2301653, 2, 2561):'A'}
print(transcript[2301653,2,2561])

A


We can also use a dictionary to group items with a common value.  The following example uses a dictionary to eliminate duplicate items in a list.  All items from the list are added into the dictionary as the key.  However, when a key that already exists in the dictionary is added, the old value is replaced by the new value.  As a result, there is no duplicate key value.

In [ ]:
classList = [2301551, 2301552, 2301551, 2301678, 2301750]
classes = {} # {courseID: number ,... }
for c in classList:
    if c in classes:
        classes[c]=classes[c]+1
    else:
        classes[c]=1    
for k in classes:
    print(k, classes[k])

2301551 2
2301552 1
2301678 1
2301750 1


### Exercises

Write a program that reads a student number and semester number (1,2, or 3) as input and calculates the registration fee for the student.

*In the student number:* YYLXXXXXFF


YY is the year that the student gets into the university.

L=1,2,3,4 means undergraduate student
L=7 means graduate student

FF is the faculty code.  

Only consider 22 for Faculty of Arts, and 23 for Faculty of Science.

Use the fee in www.chula.ac.th/admissions/tuition-and-fees/ and store this table in a **dictionary**.


In [ ]:
fee = {(22, 48, 1, 1): 12000, (22, 48, 1, 2): 12000, (22, 48, 2, 1): 12000, (22, 48, 2, 2): 12000, (22, 48, 3, 1): 12000, (22, 48, 3, 2): 12000, (22, 48, 4, 1): 12000, (22, 48, 4, 2): 12000, (22, 49, 1, 1): 12000, (22, 49, 1, 2): 12000, (22, 49, 2, 1): 12000, (22, 49, 2, 2): 12000, (22, 49, 3, 1): 12000, (22, 49, 3, 2): 12000, (22, 49, 4, 1): 12000, (22, 49, 4, 2): 12000, (22, 48, 1, 3): 4000, (22, 48, 2, 3): 4000, (22, 48, 3, 3): 4000, (22, 48, 4, 3): 4000, (22, 49, 1, 3): 4000, (22, 49, 2, 3): 4000, (22, 49, 3, 3): 4000, (22, 49, 4, 3): 4000, (22, 48, 7, 1): 16500, (22, 48, 7, 2): 16500, (22, 49, 7, 1): 16500, (22, 49, 7, 2): 16500, (22, 48, 7, 3): 6000, (22, 49, 7, 3): 6000, (22, 50, 1, 1): 14500, (22, 50, 1, 2): 14500, (22, 50, 2, 1): 14500, (22, 50, 2, 2): 14500, (22, 50, 3, 1): 14500, (22, 50, 3, 2): 14500, (22, 50, 4, 1): 14500, (22, 50, 4, 2): 14500, (22, 51, 1, 1): 14500, (22, 51, 1, 2): 14500, (22, 51, 2, 1): 14500, (22, 51, 2, 2): 14500, (22, 51, 3, 1): 14500, (22, 51, 3, 2): 14500, (22, 51, 4, 1): 14500, (22, 51, 4, 2): 14500, (22, 52, 1, 1): 14500, (22, 52, 1, 2): 14500, (22, 52, 2, 1): 14500, (22, 52, 2, 2): 14500, (22, 52, 3, 1): 14500, (22, 52, 3, 2): 14500, (22, 52, 4, 1): 14500, (22, 52, 4, 2): 14500, (22, 53, 1, 1): 14500, (22, 53, 1, 2): 14500, (22, 53, 2, 1): 14500, (22, 53, 2, 2): 14500, (22, 53, 3, 1): 14500, (22, 53, 3, 2): 14500, (22, 53, 4, 1): 14500, (22, 53, 4, 2): 14500, (22, 54, 1, 1): 14500, (22, 54, 1, 2): 14500, (22, 54, 2, 1): 14500, (22, 54, 2, 2): 14500, (22, 54, 3, 1): 14500, (22, 54, 3, 2): 14500, (22, 54, 4, 1): 14500, (22, 54, 4, 2): 14500, (22, 55, 1, 1): 14500, (22, 55, 1, 2): 14500, (22, 55, 2, 1): 14500, (22, 55, 2, 2): 14500, (22, 55, 3, 1): 14500, (22, 55, 3, 2): 14500, (22, 55, 4, 1): 14500, (22, 55, 4, 2): 14500, (22, 50, 1, 3): 4500, (22, 50, 2, 3): 4500, (22, 50, 3, 3): 4500, (22, 50, 4, 3): 4500, (22, 51, 1, 3): 4500, (22, 51, 2, 3): 4500, (22, 51, 3, 3): 4500, (22, 51, 4, 3): 4500, (22, 52, 1, 3): 4500, (22, 52, 2, 3): 4500, (22, 52, 3, 3): 4500, (22, 52, 4, 3): 4500, (22, 53, 1, 3): 4500, (22, 53, 2, 3): 4500, (22, 53, 3, 3): 4500, (22, 53, 4, 3): 4500, (22, 54, 1, 3): 4500, (22, 54, 2, 3): 4500, (22, 54, 3, 3): 4500, (22, 54, 4, 3): 4500, (22, 55, 1, 3): 4500, (22, 55, 2, 3): 4500, (22, 55, 3, 3): 4500, (22, 55, 4, 3): 4500, (22, 50, 7, 1): 19000, (22, 50, 7, 2): 19000, (22, 51, 7, 1): 19000, (22, 51, 7, 2): 19000, (22, 52, 7, 1): 19000, (22, 52, 7, 2): 19000, (22, 53, 7, 1): 19000, (22, 53, 7, 2): 19000, (22, 54, 7, 1): 19000, (22, 54, 7, 2): 19000, (22, 55, 7, 1): 19000, (22, 55, 7, 2): 19000, (22, 50, 7, 3): 7000, (22, 51, 7, 3): 7000, (22, 52, 7, 3): 7000, (22, 53, 7, 3): 7000, (22, 54, 7, 3): 7000, (22, 55, 7, 3): 7000, (22, 56, 1, 1): 17000, (22, 56, 1, 2): 17000, (22, 56, 2, 1): 17000, (22, 56, 2, 2): 17000, (22, 56, 3, 1): 17000, (22, 56, 3, 2): 17000, (22, 56, 4, 1): 17000, (22, 56, 4, 2): 17000, (22, 57, 1, 1): 17000, (22, 57, 1, 2): 17000, (22, 57, 2, 1): 17000, (22, 57, 2, 2): 17000, (22, 57, 3, 1): 17000, (22, 57, 3, 2): 17000, (22, 57, 4, 1): 17000, (22, 57, 4, 2): 17000, (22, 58, 1, 1): 17000, (22, 58, 1, 2): 17000, (22, 58, 2, 1): 17000, (22, 58, 2, 2): 17000, (22, 58, 3, 1): 17000, (22, 58, 3, 2): 17000, (22, 58, 4, 1): 17000, (22, 58, 4, 2): 17000, (22, 59, 1, 1): 17000, (22, 59, 1, 2): 17000, (22, 59, 2, 1): 17000, (22, 59, 2, 2): 17000, (22, 59, 3, 1): 17000, (22, 59, 3, 2): 17000, (22, 59, 4, 1): 17000, (22, 59, 4, 2): 17000, (22, 60, 1, 1): 17000, (22, 60, 1, 2): 17000, (22, 60, 2, 1): 17000, (22, 60, 2, 2): 17000, (22, 60, 3, 1): 17000, (22, 60, 3, 2): 17000, (22, 60, 4, 1): 17000, (22, 60, 4, 2): 17000, (22, 61, 1, 1): 17000, (22, 61, 1, 2): 17000, (22, 61, 2, 1): 17000, (22, 61, 2, 2): 17000, (22, 61, 3, 1): 17000, (22, 61, 3, 2): 17000, (22, 61, 4, 1): 17000, (22, 61, 4, 2): 17000, (22, 62, 1, 1): 17000, (22, 62, 1, 2): 17000, (22, 62, 2, 1): 17000, (22, 62, 2, 2): 17000, (22, 62, 3, 1): 17000, (22, 62, 3, 2): 17000, (22, 62, 4, 1): 17000, (22, 62, 4, 2): 17000, (22, 63, 1, 1): 17000, (22, 63, 1, 2): 17000, (22, 63, 2, 1): 17000, (22, 63, 2, 2): 17000, (22, 63, 3, 1): 17000, (22, 63, 3, 2): 17000, (22, 63, 4, 1): 17000, (22, 63, 4, 2): 17000, (22, 56, 1, 3): 5250, (22, 56, 2, 3): 5250, (22, 56, 3, 3): 5250, (22, 56, 4, 3): 5250, (22, 57, 1, 3): 5250, (22, 57, 2, 3): 5250, (22, 57, 3, 3): 5250, (22, 57, 4, 3): 5250, (22, 58, 1, 3): 5250, (22, 58, 2, 3): 5250, (22, 58, 3, 3): 5250, (22, 58, 4, 3): 5250, (22, 59, 1, 3): 5250, (22, 59, 2, 3): 5250, (22, 59, 3, 3): 5250, (22, 59, 4, 3): 5250, (22, 60, 1, 3): 5250, (22, 60, 2, 3): 5250, (22, 60, 3, 3): 5250, (22, 60, 4, 3): 5250, (22, 61, 1, 3): 5250, (22, 61, 2, 3): 5250, (22, 61, 3, 3): 5250, (22, 61, 4, 3): 5250, (22, 62, 1, 3): 5250, (22, 62, 2, 3): 5250, (22, 62, 3, 3): 5250, (22, 62, 4, 3): 5250, (22, 63, 1, 3): 5250, (22, 63, 2, 3): 5250, (22, 63, 3, 3): 5250, (22, 63, 4, 3): 5250, (22, 56, 7, 1): 23000, (22, 56, 7, 2): 23000, (22, 57, 7, 1): 23000, (22, 57, 7, 2): 23000, (22, 58, 7, 1): 23000, (22, 58, 7, 2): 23000, (22, 59, 7, 1): 23000, (22, 59, 7, 2): 23000, (22, 60, 7, 1): 23000, (22, 60, 7, 2): 23000, (22, 61, 7, 1): 23000, (22, 61, 7, 2): 23000, (22, 62, 7, 1): 23000, (22, 62, 7, 2): 23000, (22, 63, 7, 1): 23000, (22, 63, 7, 2): 23000, (22, 56, 7, 3): 7750, (22, 57, 7, 3): 7750, (22, 58, 7, 3): 7750, (22, 59, 7, 3): 7750, (22, 60, 7, 3): 7750, (22, 61, 7, 3): 7750, (22, 62, 7, 3): 7750, (22, 63, 7, 3): 7750, (23, 48, 1, 1): 16000, (23, 48, 1, 2): 16000, (23, 48, 2, 1): 16000, (23, 48, 2, 2): 16000, (23, 48, 3, 1): 16000, (23, 48, 3, 2): 16000, (23, 48, 4, 1): 16000, (23, 48, 4, 2): 16000, (23, 49, 1, 1): 16000, (23, 49, 1, 2): 16000, (23, 49, 2, 1): 16000, (23, 49, 2, 2): 16000, (23, 49, 3, 1): 16000, (23, 49, 3, 2): 16000, (23, 49, 4, 1): 16000, (23, 49, 4, 2): 16000, (23, 48, 1, 3): 4000, (23, 48, 2, 3): 4000, (23, 48, 3, 3): 4000, (23, 48, 4, 3): 4000, (23, 49, 1, 3): 4000, (23, 49, 2, 3): 4000, (23, 49, 3, 3): 4000, (23, 49, 4, 3): 4000, (23, 48, 7, 1): 22500, (23, 48, 7, 2): 22500, (23, 49, 7, 1): 22500, (23, 49, 7, 2): 22500, (23, 48, 7, 3): 6000, (23, 49, 7, 3): 6000, (23, 50, 1, 1): 18000, (23, 50, 1, 2): 18000, (23, 50, 2, 1): 18000, (23, 50, 2, 2): 18000, (23, 50, 3, 1): 18000, (23, 50, 3, 2): 18000, (23, 50, 4, 1): 18000, (23, 50, 4, 2): 18000, (23, 51, 1, 1): 18000, (23, 51, 1, 2): 18000, (23, 51, 2, 1): 18000, (23, 51, 2, 2): 18000, (23, 51, 3, 1): 18000, (23, 51, 3, 2): 18000, (23, 51, 4, 1): 18000, (23, 51, 4, 2): 18000, (23, 52, 1, 1): 18000, (23, 52, 1, 2): 18000, (23, 52, 2, 1): 18000, (23, 52, 2, 2): 18000, (23, 52, 3, 1): 18000, (23, 52, 3, 2): 18000, (23, 52, 4, 1): 18000, (23, 52, 4, 2): 18000, (23, 53, 1, 1): 18000, (23, 53, 1, 2): 18000, (23, 53, 2, 1): 18000, (23, 53, 2, 2): 18000, (23, 53, 3, 1): 18000, (23, 53, 3, 2): 18000, (23, 53, 4, 1): 18000, (23, 53, 4, 2): 18000, (23, 54, 1, 1): 18000, (23, 54, 1, 2): 18000, (23, 54, 2, 1): 18000, (23, 54, 2, 2): 18000, (23, 54, 3, 1): 18000, (23, 54, 3, 2): 18000, (23, 54, 4, 1): 18000, (23, 54, 4, 2): 18000, (23, 55, 1, 1): 18000, (23, 55, 1, 2): 18000, (23, 55, 2, 1): 18000, (23, 55, 2, 2): 18000, (23, 55, 3, 1): 18000, (23, 55, 3, 2): 18000, (23, 55, 4, 1): 18000, (23, 55, 4, 2): 18000, (23, 50, 1, 3): 4500, (23, 50, 2, 3): 4500, (23, 50, 3, 3): 4500, (23, 50, 4, 3): 4500, (23, 51, 1, 3): 4500, (23, 51, 2, 3): 4500, (23, 51, 3, 3): 4500, (23, 51, 4, 3): 4500, (23, 52, 1, 3): 4500, (23, 52, 2, 3): 4500, (23, 52, 3, 3): 4500, (23, 52, 4, 3): 4500, (23, 53, 1, 3): 4500, (23, 53, 2, 3): 4500, (23, 53, 3, 3): 4500, (23, 53, 4, 3): 4500, (23, 54, 1, 3): 4500, (23, 54, 2, 3): 4500, (23, 54, 3, 3): 4500, (23, 54, 4, 3): 4500, (23, 55, 1, 3): 4500, (23, 55, 2, 3): 4500, (23, 55, 3, 3): 4500, (23, 55, 4, 3): 4500, (23, 50, 7, 1): 26000, (23, 50, 7, 2): 26000, (23, 51, 7, 1): 26000, (23, 51, 7, 2): 26000, (23, 52, 7, 1): 26000, (23, 52, 7, 2): 26000, (23, 53, 7, 1): 26000, (23, 53, 7, 2): 26000, (23, 54, 7, 1): 26000, (23, 54, 7, 2): 26000, (23, 55, 7, 1): 26000, (23, 55, 7, 2): 26000, (23, 50, 7, 3): 7000, (23, 51, 7, 3): 7000, (23, 52, 7, 3): 7000, (23, 53, 7, 3): 7000, (23, 54, 7, 3): 7000, (23, 55, 7, 3): 7000, (23, 56, 1, 1): 21000, (23, 56, 1, 2): 21000, (23, 56, 2, 1): 21000, (23, 56, 2, 2): 21000, (23, 56, 3, 1): 21000, (23, 56, 3, 2): 21000, (23, 56, 4, 1): 21000, (23, 56, 4, 2): 21000, (23, 57, 1, 1): 21000, (23, 57, 1, 2): 21000, (23, 57, 2, 1): 21000, (23, 57, 2, 2): 21000, (23, 57, 3, 1): 21000, (23, 57, 3, 2): 21000, (23, 57, 4, 1): 21000, (23, 57, 4, 2): 21000, (23, 58, 1, 1): 21000, (23, 58, 1, 2): 21000, (23, 58, 2, 1): 21000, (23, 58, 2, 2): 21000, (23, 58, 3, 1): 21000, (23, 58, 3, 2): 21000, (23, 58, 4, 1): 21000, (23, 58, 4, 2): 21000, (23, 59, 1, 1): 21000, (23, 59, 1, 2): 21000, (23, 59, 2, 1): 21000, (23, 59, 2, 2): 21000, (23, 59, 3, 1): 21000, (23, 59, 3, 2): 21000, (23, 59, 4, 1): 21000, (23, 59, 4, 2): 21000, (23, 60, 1, 1): 21000, (23, 60, 1, 2): 21000, (23, 60, 2, 1): 21000, (23, 60, 2, 2): 21000, (23, 60, 3, 1): 21000, (23, 60, 3, 2): 21000, (23, 60, 4, 1): 21000, (23, 60, 4, 2): 21000, (23, 61, 1, 1): 21000, (23, 61, 1, 2): 21000, (23, 61, 2, 1): 21000, (23, 61, 2, 2): 21000, (23, 61, 3, 1): 21000, (23, 61, 3, 2): 21000, (23, 61, 4, 1): 21000, (23, 61, 4, 2): 21000, (23, 62, 1, 1): 21000, (23, 62, 1, 2): 21000, (23, 62, 2, 1): 21000, (23, 62, 2, 2): 21000, (23, 62, 3, 1): 21000, (23, 62, 3, 2): 21000, (23, 62, 4, 1): 21000, (23, 62, 4, 2): 21000, (23, 63, 1, 1): 21000, (23, 63, 1, 2): 21000, (23, 63, 2, 1): 21000, (23, 63, 2, 2): 21000, (23, 63, 3, 1): 21000, (23, 63, 3, 2): 21000, (23, 63, 4, 1): 21000, (23, 63, 4, 2): 21000, (23, 56, 1, 3): 5250, (23, 56, 2, 3): 5250, (23, 56, 3, 3): 5250, (23, 56, 4, 3): 5250, (23, 57, 1, 3): 5250, (23, 57, 2, 3): 5250, (23, 57, 3, 3): 5250, (23, 57, 4, 3): 5250, (23, 58, 1, 3): 5250, (23, 58, 2, 3): 5250, (23, 58, 3, 3): 5250, (23, 58, 4, 3): 5250, (23, 59, 1, 3): 5250, (23, 59, 2, 3): 5250, (23, 59, 3, 3): 5250, (23, 59, 4, 3): 5250, (23, 60, 1, 3): 5250, (23, 60, 2, 3): 5250, (23, 60, 3, 3): 5250, (23, 60, 4, 3): 5250, (23, 61, 1, 3): 5250, (23, 61, 2, 3): 5250, (23, 61, 3, 3): 5250, (23, 61, 4, 3): 5250, (23, 62, 1, 3): 5250, (23, 62, 2, 3): 5250, (23, 62, 3, 3): 5250, (23, 62, 4, 3): 5250, (23, 63, 1, 3): 5250, (23, 63, 2, 3): 5250, (23, 63, 3, 3): 5250, (23, 63, 4, 3): 5250, (23, 56, 7, 1): 31000, (23, 56, 7, 2): 31000, (23, 57, 7, 1): 31000, (23, 57, 7, 2): 31000, (23, 58, 7, 1): 31000, (23, 58, 7, 2): 31000, (23, 59, 7, 1): 31000, (23, 59, 7, 2): 31000, (23, 60, 7, 1): 31000, (23, 60, 7, 2): 31000, (23, 61, 7, 1): 31000, (23, 61, 7, 2): 31000, (23, 62, 7, 1): 31000, (23, 62, 7, 2): 31000, (23, 63, 7, 1): 31000, (23, 63, 7, 2): 31000, (23, 56, 7, 3): 7750, (23, 57, 7, 3): 7750, (23, 58, 7, 3): 7750, (23, 59, 7, 3): 7750, (23, 60, 7, 3): 7750, (23, 61, 7, 3): 7750, (23, 62, 7, 3): 7750, (23, 63, 7, 3): 7750}
Input = input("The student number and semester number:")
studentID, semester = [int(_) for _ in Input.split(' ')]
YY = studentID // 10**8
L = studentID // 10**7 % 10
FF = studentID % 10**2
print(f"The registration fee for the student', {fee[(FF, YY, L, semester)]}")

The student number and semester number:6278015323 2
The registration fee for the student', 31000


Write a program to read a text file and count the number of each word in the file, a using dictionary.

In [ ]:
from collections import defaultdict
di = defaultdict(int)
with open('test.txt') as f:
   for line in f:
       for w in line.strip().split():
           di[w]+=1
print(di)

defaultdict(<class 'int'>, {'John': 3, 'is': 2, 'a': 3, 'nice': 2, 'person': 2, 'He': 1, 'would': 1, 'like': 1, 'to': 1, 'do': 1, 'anything': 1, 'for': 1, 'stranger': 1, 'If': 1, 'you': 2, 'want': 1, 'any': 1, 'hep': 1, 'from': 1, 'him': 1, ',': 1, 'could': 1, 'contact': 1})


In [ ]:
with open('test.txt', 'r') as f:
  w = {}
  for line in f:
    for word in line.split():
      if word in w:
        w[word] += 1
      else:
        w[word] = 1
print(w)

Write a program that reads a CSV file that each line contains student ID, course number and section number. For example,

`6274565423 , 2301551, 1`

Then, use a **dictionary** to generate a registration list in which each element is a list of students registered in each course, grouped by section, as shown below.  The following list contains 2 courses, 2301551 and 2301170. Each course has 2 sections.

`[['2301551',[['1',['6274565423',...]],['2',['6134567823',...]]]], ['2301170',[['1',[...]],['2',[...]]]]]`

In [ ]:
w = {}
with open('new.csv', 'r') as f:
  for line in f:
    ID, course, section = [_.strip() for _ in line.split(',')]
    if course in w:
      if section in w[course]:
        w[course][section].append(ID)
      else:
        w[course].update({section: [ID]})
    else:
        w.update({course: {section: [ID]}})

print(w)

{'2301551': {'1': ['6274565423'], '2': ['6134567823', '6278015323']}, '2301170': {'1': ['6389278323'], '2': ['6128368623', '6374565323']}}


## Dictionary of Dictionaries

In a dictionary, a value can also be another dictionary. In the following dictionary,

`{6235122623: {2301170:'B+', 2301172:'A'}, 6274522623: {2301551:'S'}}`

* 6235122623 is associated to the dictionary  {2301170:'B+', 2301172:'A'} and

* 6274522623 is associated to {2301551:'S'}

In [ ]:
transcripts = {6235122623: {2301170:'B+', 2301172:'A'}, 6274522623: {2301551:'S', 2301552:'S'}, 6232548923: {2301170:'D', 2301172:'W'}}
x=transcripts[6235122623]
print(transcripts[6235122623][2301170])

{2301170: 'B+', 2301172: 'A'}
B+


### Exercises

Write a program that creates a dictionary that stores the student transcript from data read from an input file.

Example of the input file:
```
6212345623 2301170 3.0
6212222223 2301107 3.5
6212345623 2301172 4.0
6212345623 2301345 3.0
```

This dictionary must allow easy search for:

*   all records of a given student, and
*   the grade that a student got for a course.

In [ ]:
with open('test.csv', 'r') as f:
  w = {}
  types = [int, int, float]
  for line in f:
    studentID, course, grade = [f(x) for (f, x) in zip(types,line.split(' '))]
    if studentID in w:
      w[studentID][course] = grade
    else:
      w[studentID] = {course: grade}
print(w)

{6212345623: {2301170: 3.0, 2301172: 4.0, 2301345: 3.0}, 6212222223: {2301107: 3.5}}


Write a program to read a student transcript from a dictionary from the previous problem and the number of credits for all courses stored in another dictionary (You can make up this dictionary).  Then calculate GPAX for each student.

In [ ]:
w = {6212345623: {2301170: 3.0, 2301172: 4.0, 2301345: 3.0}, 6212222223: {2301107: 3.5}}
courses = {2301170: 1, 2301172: 3, 2301345: 2, 2301107: 2}
GPAX = {}
for ID in w:
    total: int = 0
    i = 0
    for course, grade in w[ID].items():
        total += grade * courses[course]
        i += courses[course]
    GPAX[ID] = total / i
print(GPAX)   

{6212345623: 3.5, 6212222223: 3.5}


Redo the previous exercise **Registration fee**, using dictionary of dictionaries.

In [ ]:
Year = {year: 48 for year in range(48, 50)}
Year.update({year:50 for year in range(50, 56)})
Year.update({year:56 for year in range(56, 64)})

level = {l:"uundergrad"  for l in range(1, 5)}
level.update({7:'grad'})

fee = {22: {48: {'undergrad':{1:12000, 2:12000, 3:4000}, 'grad': {1:16500, 2:16500, 3:6000}},
            50: {'undergrad':{1:14500, 2:14500, 3:4500}, 'grad': {1:19000, 2:19000, 3:7000}},
            56: {'undergrad':{1:17000, 2:17000, 3:5250}, 'grad': {1:23000, 2:23000, 3:7750}}},
       23: {48: {'undergrad':{1:16000, 2:16000, 3:4000}, 'grad': {1:22500, 2:22500, 3:6000}},
            50: {'undergrad':{1:18000, 2:18000, 3:4500}, 'grad': {1:26000, 2:26000, 3:7000}},
            56: {'undergrad':{1:21000, 2:21000, 3:5250}, 'grad': {1:31000, 2:31000, 3:7750}}}}

print(fee)

Input = input('please enter <a student number, semester number>: ')
studentID, semester = [int(_) for _ in Input.split(' ')]
YY = studentID // 10**8
L = studentID // 10**7 % 10
FF = studentID % 10**2
print(f"Registration fee = {fee[FF][Year[YY]][level[L]][semester]}")

{22: {48: {'undergrad': {1: 12000, 2: 12000, 3: 4000}, 'grad': {1: 16500, 2: 16500, 3: 6000}}, 50: {'undergrad': {1: 14500, 2: 14500, 3: 4500}, 'grad': {1: 19000, 2: 19000, 3: 7000}}, 56: {'undergrad': {1: 17000, 2: 17000, 3: 5250}, 'grad': {1: 23000, 2: 23000, 3: 7750}}}, 23: {48: {'undergrad': {1: 16000, 2: 16000, 3: 4000}, 'grad': {1: 22500, 2: 22500, 3: 6000}}, 50: {'undergrad': {1: 18000, 2: 18000, 3: 4500}, 'grad': {1: 26000, 2: 26000, 3: 7000}}, 56: {'undergrad': {1: 21000, 2: 21000, 3: 5250}, 'grad': {1: 31000, 2: 31000, 3: 7750}}}}
please enter <a student number, semester number>: 6278015323 2
Registration fee = 31000


Dict Comprehensions


In [ ]:
dct = {k:k*k for k in range(8) if k!=k*k}
print(dct)

{2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49}
